/*CREACION DE LA BASE DE DATOS*/
CREATE DATABASE dbImagenes

/*SELECCION DE LA BASE DE DATOS*/
USE dbImagenes

/*CREACION DE LA TABLA*/
CREATE TABLE IMAGENES
( ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  IMAGEN VARCHAR(50) NOT NULL,
  DESCRIPCION VARCHAR(50) NOT NULL
)
 /*AGREGADO DE DATOS*/
 INSERT INTO IMAGENES("IMAGEN", "DESCRIPCION") VALUES('real.JPG','REAL MADRID')
 INSERT INTO IMAGENES("IMAGEN", "DESCRIPCION") VALUES('estreno.JPG', 'MOTO NUEVA')
 INSERT INTO IMAGENES("IMAGEN", "DESCRIPCION") VALUES('mls.JPG', 'EQUIPAZO')

 INSERT INTO IMAGENES("IMAGEN", "DESCRIPCION") VALUES('editado.JPG', 'DISTRAIDO')

 /*CONSULTAR DATOS*/
 SELECT * FROM IMAGENES